# Generated by Django 4.1.7 on 2023-04-10 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0008_remove_events_association_events_association_group'),
        ('Associations', '0015_alter_associations_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('INVOICE_CREATED', 'Invoice Created'), ('INVOICE_SUCCESS', 'Invoice Success'), ('INVOICE_FAILED', 'Invoice Failed'), ('ASSOCIATION_CREATED', 'Association Created'), ('ASSOCIATION_APPROVAL_ACCEPTED', 'Association Approval Accepted'), ('ASSOCIATION_APPROVAL_REJECTED', 'Association Approval Rejected'), ('ASSOCIATION_INVITATION', 'Association Invitation'), ('ASSOCIATION_INVITATION_ACCEPTED', 'Association Invitation Accepted'), ('ASSOCIATION_INVITATION_REJECTED', 'Association Invitation Rejected'), ('ASSOCIATION_PERMISSION_TO_MANAGER', 'Association Permission to Manager'), ('ASSOCIATION_PERMISSION_TO_MEMBER', 'Association Permission to Member'), ('ASSOCIATION_POSTED_NEW_EVENT', 'Association Posted New Event'), ('EVENT_INVITATION', 'Event Invitation'), ('EVENT_INVITATION_ACCEPTED', 'Event Invitation Accepted'), ('EVENT_INVITATION_REJECTED', 'Event Invitation Rejected'), ('EVENT_ENROLLED_SUCCESS', 'Event Enrolled Success'), ('EVENT_ENROLLED_FAILED', 'Event Enrolled Failed'), ('EVENT_POINT_RECEIVED', 'Event Point Received'), ('EVENT_CERTIFICATE_RECEIVED', 'Event Certificate Received'), ('EVENT_REMINDER_BEFORE', 'Event Reminder Before'), ('EVENT_REMINDER_STARTED', 'Event Reminder Started'), ('EVENT_REMINDER_ENDED', 'Event Reminder Ended'), ('EVENT_GOT_REVIEW', 'Event Got Review'), ('EVENT_GOT_ATTENDED', 'Event Got Attended'), ('EVENT_GOT_REACTION', 'Event Got Reaction'), ('NEW_ACCOUNT_MESSAGE', 'New Account Message')], db_index=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Associations.associations')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.events')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Notifications',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('type', models.TextField(choices=[('ASSOCIATION_INVITATION_ACCEPT', 'Association Invitation Accept'), ('ASSOCIATION_INVITATION_REJECT', 'Association Invitation Reject'), ('ASSOCIATION_DETAIL', 'Association Detail'), ('EVENT_INVITATION_ACCEPT', 'Event Invitation Accept'), ('EVENT_INVITATION_REJECT', 'Event Invitation Reject'), ('EVENT_STREAM_DETAIL', 'Event Stream Detail'), ('EVENT_DETAIL', 'Event Detail'), ('INVOICE_DETAIL', 'Invoice Detail'), ('PROFILE_POINT_DETAIL', 'Profile Point Detail'), ('PROFILE_CERTIFICATE_DETAIL', 'Profile Certificate Detail')], db_index=True)),
                ('style', models.TextField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('SLATE', 'Slate'), ('BLACK', 'Black')])),
                ('is_priority', models.BooleanField(blank=True, default=None, null=True)),
                ('target_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NotificationHandler.usernotification')),
            ],
            options={
                'verbose_name_plural': 'User Notifications Action',
            },
        ),
    ]
