# Generated by Django 4.1.7 on 2023-03-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0004_remove_associations_is_disabled_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='associations',
            constraint=models.UniqueConstraint(fields=('approval', 'user'), name='association_user_unique'),
        ),
    ]
