# Generated by Django 4.1.7 on 2023-03-31 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0005_associations_association_user_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='associations',
            name='association_user_unique',
        ),
        migrations.RemoveField(
            model_name='associations',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='associationsapprovalrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='associationsapprovalrequest',
            name='association',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Associations.associations'),
            preserve_default=False,
        ),
    ]
