# Generated by Django 4.1.7 on 2023-03-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0006_remove_associations_association_user_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationsapprovalrequest',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
