# Generated by Django 4.1.7 on 2023-04-01 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0007_alter_associationsapprovalrequest_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationsapprovalrequest',
            name='association',
        ),
        migrations.AddField(
            model_name='associations',
            name='approval',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Associations.associationsapprovalrequest'),
            preserve_default=False,
        ),
    ]
