# Generated by Django 4.1.7 on 2023-04-01 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0009_alter_associations_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associations',
            name='approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Associations.associationsapprovalrequest'),
        ),
    ]
