# Generated by Django 4.1.7 on 2023-04-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0010_alter_associations_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationsgroup',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='associationsgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
