# Generated by Django 4.1.7 on 2023-04-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0011_associationsgroup_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associations',
            name='user',
        ),
        migrations.AddField(
            model_name='associationsgroup',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
