# Generated by Django 4.1.7 on 2023-04-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0012_remove_associations_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associations',
            name='website',
            field=models.URLField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
