# Generated by Django 4.1.7 on 2023-04-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0014_associationsapprovalrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associations',
            name='approval',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Associations.associationsapprovalrequest'),
            preserve_default=False,
        ),
    ]
