# Generated by Django 4.1.7 on 2023-05-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0015_alter_associations_approval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationsgroup',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Associations Group'},
        ),
    ]
