# Generated by Django 4.1.7 on 2023-03-27 16:26

import Events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_rename_url_custom_events_url_homepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='banner',
            field=models.ImageField(max_length=500, upload_to=Events.models.banner_events_upload_handler),
        ),
    ]
