# Generated by Django 4.1.7 on 2023-03-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_alter_events_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='max_audience',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
