# Generated by Django 4.1.7 on 2023-03-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_events_max_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
