# Generated by Django 4.1.7 on 2023-03-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0001_initial'),
        ('Events', '0005_alter_events_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Associations.associations'),
            preserve_default=False,
        ),
    ]
