# Generated by Django 4.1.7 on 2023-04-05 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Associations', '0012_remove_associations_user_and_more'),
        ('Events', '0007_alter_events_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='association',
        ),
        migrations.AddField(
            model_name='events',
            name='association_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Associations.associationsgroup'),
        ),
    ]
