# Generated by Django 4.1.7 on 2023-04-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_remove_events_association_events_association_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.events')),
            ],
            options={
                'verbose_name_plural': 'Events Coverage Outline',
            },
        ),
        migrations.AddConstraint(
            model_name='eventscoverage',
            constraint=models.UniqueConstraint(fields=('event', 'coverage'), name='unique_event_coverage'),
        ),
    ]
