# Generated by Django 4.1.7 on 2023-04-14 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0009_eventscoverage_eventscoverage_unique_event_coverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attended', models.BooleanField(blank=True, default=None, null=True)),
                ('attended_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Events User Attendee',
            },
        ),
        migrations.AddConstraint(
            model_name='eventsattendee',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_user_attendees'),
        ),
    ]
