# Generated by Django 4.1.7 on 2023-04-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0011_eventsuserregistered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsuserregistered',
            options={'verbose_name_plural': 'Events User Registered'},
        ),
    ]
