# Generated by Django 4.1.7 on 2023-05-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_events_banner_lazy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsextendedurl',
            old_name='url_title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='eventsextendedurl',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventsextendedurl',
            name='url',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='eventsextendedurl',
            constraint=models.UniqueConstraint(fields=('event', 'name', 'url'), name='unique_event_url'),
        ),
    ]
