# Generated by Django 4.1.7 on 2023-05-03 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0016_events_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsextendedurl',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_extended_url', to='Events.events'),
        ),
    ]
