# Generated by Django 4.1.7 on 2023-04-14 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Events', '0012_alter_eventsuserregistered_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceUserEventRegistered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('status', models.TextField(choices=[('WAITING', 'Waiting'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='WAITING')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.eventsuserregistered')),
            ],
            options={
                'verbose_name_plural': 'Invoice for User Event Registered',
            },
        ),
        migrations.CreateModel(
            name='InvoiceEventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('status', models.TextField(choices=[('WAITING', 'Waiting'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='WAITING')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.events')),
            ],
            options={
                'verbose_name_plural': 'Invoice for Event Publish',
            },
        ),
    ]
