# Generated by Django 4.1.7 on 2023-05-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0003_alter_invoiceeventpost_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceeventpost',
            options={'ordering': ['updated_at'], 'verbose_name_plural': 'Invoice for Event Publish'},
        ),
    ]
