# Generated by Django 4.1.7 on 2023-05-03 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0004_alter_invoiceeventpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceusereventregistered',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 1, 29, 46, 932427, tzinfo=datetime.timezone.utc)),
        ),
    ]
