# Generated by Django 4.1.7 on 2023-05-03 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0005_invoiceusereventregistered_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceusereventregistered',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 1, 30, 22, 276573, tzinfo=datetime.timezone.utc)),
        ),
    ]
