# Generated by Django 4.1.7 on 2023-05-06 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0006_alter_invoiceusereventregistered_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceeventpost',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 5, 16, 51, 777765, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoiceusereventregistered',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 5, 16, 51, 778766, tzinfo=datetime.timezone.utc)),
        ),
    ]
