# Generated by Django 4.1.7 on 2023-05-16 03:00

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0007_invoiceeventpost_expired_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceeventpost',
            name='midtrans_token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceeventpost',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, null=True),
        ),
        migrations.AddField(
            model_name='invoiceusereventregistered',
            name='midtrans_token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceusereventregistered',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceeventpost',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(
                2023, 5, 17, 2, 59, 58, 507872, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invoiceusereventregistered',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(
                2023, 5, 17, 2, 59, 58, 508873, tzinfo=datetime.timezone.utc)),
        ),
    ]
