# Generated by Django 4.1.7 on 2023-05-16 03:00

from django.db import models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0009_auto_populate_uuid_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceeventpost',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, unique=True),
        ),
        migrations.AlterField(
            model_name='invoiceusereventregistered',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, unique=True),
        ),
    ]
