# Generated by Django 4.1.7 on 2023-03-22 02:19

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.user_avatar_upload_handler),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('H', 'Hide Gender')], default='H', max_length=1),
        ),
    ]
