# Generated by Django 4.1.7 on 2023-03-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options_user_avatar_user_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'User'},
        ),
    ]
